//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMainLog
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string AdminName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> ItemId { get; set; }
    }
}
