//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubmittedAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubmittedAssignment()
        {
            this.tblLogs = new HashSet<tblLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Routine_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<System.DateTime> Submitted_Date { get; set; }
        public Nullable<int> Checked_Status { get; set; }
        public Nullable<int> Feedback_Status { get; set; }
        public Nullable<int> Marking { get; set; }
        public Nullable<int> Assignmnet_Location { get; set; }
    
        public virtual tblAssignmentRoutine tblAssignmentRoutine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLog> tblLogs { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
