//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentRoutineRelation
    {
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> RoutineId { get; set; }
    
        public virtual tblAssignmentRoutine tblAssignmentRoutine { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
