//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent()
        {
            this.tblStudentRoutineRelations = new HashSet<tblStudentRoutineRelation>();
            this.tblSubmittedAssignments = new HashSet<tblSubmittedAssignment>();
        }
    
        public int Student_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> YearBatchId { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
        public Nullable<int> Section_Id { get; set; }
        public Nullable<int> Semester_Id { get; set; }
    
        public virtual tblFaculty tblFaculty { get; set; }
        public virtual tblSection tblSection { get; set; }
        public virtual tblSemester tblSemester { get; set; }
        public virtual tblYearBatch tblYearBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentRoutineRelation> tblStudentRoutineRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubmittedAssignment> tblSubmittedAssignments { get; set; }
    }
}
